import google closure library so that mocha can refer
ES6 import didn't work because of this error:

_googleClosureLibraryClosureGoogBootstrapNodejs2['default'].require('goog.arra
                                                            ^
TypeError: undefined is not a function